In [ ]:
#treaaditional way to find mean of a
w=[1,2,3,4,5,6,7,8,9]
a=sum(w)
b=len(w)
mean=a/b
print(mean)
print(w)

5.0
[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [ ]:
import numpy as np

In [ ]:
#converting normal list into array
num=[2,3,4,5,6,7,8,9,1]
np_data=np.array(num)
print(np_data)

[2 3 4 5 6 7 8 9 1]


In [ ]:
#getting mean of array using np.mean()
data=np.array([1,2,2,3,3,3,4,5,5,5,5,6,7,7,7,8,9])
print("mean-",np.mean(data))

mean- 4.823529411764706


In [ ]:
#getting meadian of array using np.median()
print("meadian-",np.median(data))

meadian- 5.0


In [ ]:
#getting standerd deviation of array using np.std()
print("standerd deviation-",np.std(data))

standerd deviation- 2.2290935672348726


In [ ]:
#getting varience of array using np.var()
print("varience-",np.var(data))

varience- 4.968858131487889


In [ ]:
#getting minimum ,maximum of array using np.max() , np.min()
print("maximum-",np.max(data))
print("minimum-",np.min(data))

maximum- 9
minimum- 1


In [2]:
#Write a NumPy function that takes a 1D NumPy array as input and returns a new array where each element is doubled.
import numpy as np

def double_array(arr):
  return arr * 2


num=np.array([1,2,3,4,5])
convert=double_array(num)
print(num)
print(convert)

[1 2 3 4 5]
[ 2  4  6  8 10]
