In [ ]:
import numpy as np

In [ ]:
#Write a NumPy function that takes a 1D NumPy array of integers as input and returns the sum of all the even numbers in the array.

def sum_of_even_num(arr):


    even_num=arr[arr1 %2 == 0]
    return np.sum(even_num)


arr1 =np.array([1,2,3,4,5,6])
converted_num=sum_of_even_num(arr1)
print(arr1)
print(converted_num)

[1 2 3 4 5 6]
12


In [ ]:
#Write a NumPy function that takes two 1D NumPy arrays of the same length as input and returns a new array containing the element-wise product of the two input arrays.
def product(arr2 , arr3):
  return arr2 * arr3


arr2=np.array([1,2,3])
arr3=np.array([4,5,6])
product_of_array=product(arr2 ,arr3)
print(arr2)
print(arr3)
print(product_of_array)

[1 2 3]
[4 5 6]
[ 4 10 18]


In [ ]:
#Problem : Standardize Data (Z-score Normalization)
#Write a NumPy function that takes a 1D NumPy array as input and returns a new array containing the standardized values (Z-scores) of the input array.
#Standardization involves transforming the data so that it has a mean of 0 and a standard deviation of 1. The Z-score is calculated as:
#z_score = (value - mean) / standard_deviation

import numpy as np

def standerdise_value(arr):

  mean=np.mean(arr4)
  standerd_deviation=np.std(arr4)
  z_score=(arr4-mean/standerd_deviation)

  return z_score


arr4=np.array([10,20,30,40,50,60])
standerdised_value=standerdise_value(arr4)
print("input- ",arr4)
print("output- ",standerdised_value)

input-  [10 20 30 40 50 60]
output-  [ 7.95060985 17.95060985 27.95060985 37.95060985 47.95060985 57.95060985]


In [ ]:
"""Problem : Filter Outliers Using the IQR Method
Write a NumPy function that takes a 1D NumPy array as input and returns a new array with outliers removed using the Interquartile Range (IQR) method.
Here's how the IQR method works:
Calculate the first quartile (Q1) and the third quartile (Q3) of the data.
Calculate the IQR: IQR = Q3 - Q1.
Define the lower bound: lower_bound = Q1 - 1.5 * IQR.
Define the upper bound: upper_bound = Q3 + 1.5 * IQR.
Filter out values that are less than the lower bound or greater than the upper bound."""

def filterd_outliers_with_iqr(arr):


  q1=np.percentile(arr,25)
  q3=np.percentile(arr,75)
  iqr=q3-q1

  lower_bond= q1 - 1.5 * iqr
  upper_bond= q3 + 1.5 * iqr
  filterd_arr= arr[(arr>=lower_bond) & (arr<=upper_bond)]
  return filterd_arr

arr5=np.array([1,2,3,4,5,100])
filterd_data=filterd_outliers_with_iqr(arr5)
print("input- ",arr5)
print("output-",filterd_data)

input-  [  1   2   3   4   5 100]
output- [1 2 3 4 5]


In [2]:
#Question : Calculate the Range of a Feature
#Write a NumPy function that takes a 1D NumPy array (representing a feature) as input and returns the range of the feature (the difference between the maximum and minimum values).


import numpy as np

def calculate_feature(arr):
  return np.max(arr)-np.min(arr)


feature=np.array([1,3,5,6,8])
feature_range=calculate_feature(feature)
print("input:- ",feature)
print("output:-",feature_range)

input:-  [1 3 5 6 8]
output:- 7


In [3]:
#Question : Count Unique Values
#Write a NumPy function that takes a 1D NumPy array (representing a categorical feature) as input and returns the number of unique values in the array.

def calculate_unique(arr):
  return len(np.unique(arr))


catagories=np.array(["red","white","blue","white","red"])
unique_value=calculate_unique(catagories)
print("input:- ",catagories)
print("output:- ",unique_value)

input:-  ['red' 'white' 'blue' 'white' 'red']
output:-  3
