In [ ]:
import numpy as np

In [ ]:
#Write a NumPy function that takes a 1D NumPy array of integers as input and returns the sum of all the even numbers in the array.

def sum_of_even_num(arr):


    even_num=arr[arr1 %2 == 0]
    return np.sum(even_num)


arr1 =np.array([1,2,3,4,5,6])
converted_num=sum_of_even_num(arr1)
print(arr1)
print(converted_num)

[1 2 3 4 5 6]
12


In [5]:
#Write a NumPy function that takes two 1D NumPy arrays of the same length as input and returns a new array containing the element-wise product of the two input arrays.
def product(arr2 , arr3):
  return arr2 * arr3


arr2=np.array([1,2,3])
arr3=np.array([4,5,6])
product_of_array=product(arr2 ,arr3)
print(arr2)
print(arr3)
print(product_of_array)

[1 2 3]
[4 5 6]
[ 4 10 18]


In [ ]:
#Problem : Find the Maximum Value and Its Index
#Write a NumPy function that takes a 1D NumPy array as input and returns a tuple containing the maximum value in the array and its index.
def